# Site settings
title: Doing the Work...
email: nate@finchproservices.com
description: > # this means to ignore newlines until "baseurl:"
  A simple GitHub page that says, "I showed up today. I'm just doing the work..."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://finchproservices.com" # the base hostname & protocol for your site
twitter_username: n8finch
github_username:  finchps

# Build settings
markdown: kramdown
